version: '3'

services:
  jenkins:
    build: .
    container_name: jenkins-env
    user: jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./volumes/jenkins:/var/jenkins_home:rw
    networks:
      - docker_network
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube-env
    ports:
      - "9000:9000"
    volumes:
      - ./volumes/sonar/sonarqube_data:/opt/sonarqube/data
      - ./volumes/sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - ./volumes/sonar/sonarqube_logs:/opt/sonarqube/logs
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge